---
title: "Genome assembly"
author: "Darius HUISMAN"
date: "2026-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Note that this workshop is part of a general project "marine-genomics", so the initial working directory for all the data and code generated below is the file "Workshop2_assembly".

## Redbean Assembly

### Setup working directory

``` bash
mkdir redbean
cd redbean
```

### Assembly steps

Run the first step of the assembly (takes a couple minutes)

``` bash
wtdbg2 -x ont -g 5m -t 4 -i amtp4.fastq -fo amtp4
wtpoa-cns -t 4 -i amtp4.ctg.lay.gz -fo amtp4.ctg.fa
```

Inspecte assembly statistics

``` bash
assembly-stats amtp4.ctg.fa
```

Run the second step of the assembly (takes a few minutes)

``` bash
cat /pvol/data/amtp4/*.fastq > amtp4_20x.fastq
wtdbg2 -x ont -g 5m -t 4 -i amtp4_20x.fastq -fo amtp4_20x
wtpoa-cns -t 4 -i amtp4_20x.ctg.lay.gz -fo amtp4_20x.ctg.fa
```

Inspecte assembly statistics
``` bash
assembly-stats amtp4.ctg.fa
```

## Flye Assembly

Try an alternative assembler called Flye

###Setup a Flye working directory

``` bash
mkdir flye
cd flye
```

### Run Flye on both datasets

``` bash
ln -s ../redbean/amtp4.fastq .
ln -s ../redbean/amtp4_20x.fastq .
```

#### Small file
use slurm script for small files (!!! use only once !!!)

``` bash
sbatch run_flye_small.sh
```

check job status
``` bash
squeue
```
look at file generated by slurm
``` bash
tail slurm-330.out
```
follow output while it is running
``` bash
tail -f slurm-330.out
```
Inspecte assembly statistics
``` bash
assembly-stats amtp4/assembly.fasta
```

#### Large fimle
use slurm script for small files (!!! use only once !!!)
```bash
sbatch run_flye_large.sh
```
look at file generated by slurm
``` bash
tail slurm-342.out
```
follow output while it is running
``` bash
tail -f slurm-342.out
```
Inspecte assembly statistics
``` bash
assembly-stats amtp4_20x/assembly.fasta
```

## Inspect assembly graphs with Bandage

Conducted in Bandage after downloading the "assembly_graph.gfa" files from both output generated previously (so 2 files, one from "amtp4" and one from "amtp4_20x")

## Check Assembly Quality with QUAST

### Setup a Quast working directory
```bash
cd ..

mkdir quast
cd quast
```
 
### Prepare assembly data

Make two directories within the quast directory
```bash
mkdir flye_asm redbean_asm
```

Look at the contig sizes in the flye assembly to find the two largest ones
```bash
cat ../flye/amtp4_20x/assembly.fasta | bioawk -c fastx '{print $name, length($seq)}' | sort -n -k2
```
The largest two found in this case were "contig_59" and "contig_10"

Use samtools to extract these
```bash
samtools faidx ../flye/amtp4_20x/assembly.fasta contig_59 contig_10 > flye_asm/vibrio.fasta
```

Repeat the process for the redbean assembly
```bash
cat ../redbean/amtp4_20x.ctg.fa | bioawk -c fastx '{print $name, length($seq)}' | sort -n -k2
samtools faidx ../redbean/amtp4_20x.ctg.fa ctg1 ctg2 > redbean_asm/vibrio.fasta
```

Create a symbolic link to the original reads and reference assembly
```bash
ln ../flye/amtp4_20x.fastq .
ln -s /pvol/data/amtp4/reference/vibrio .
```

### Run QUAST
```bash
quast -o quast_vibrio redbean_asm/vibrio.fasta flye_asm/vibrio.fasta -L -t 4 --circos --glimmer -r vibrio/vibrio.fna --features  vibrio/vibrio.gff --nanopore amtp4_20x.fastq
```

##Optional: Mystery Repeat Region

Store results in a directory called "repeat"
```bash
mkdir ../repeat
cd ../repeat
```

### Extract repeat region sequence

### Use prokka to annotate it
Run prokka on this sequence to see if it contains any transcribed sequences
```bash
prokka --outdir prokka --prefix repeat repeat.fasta
```
Look at the tsv file that is produced
```bash
cat prokka/repeat.tsv
```
output :
locus_tag       ftype   length_bp       gene    EC_number       COG     product
AMFJKEBI_00001  tRNA    76                              tRNA-Asp(gtc)
AMFJKEBI_00002  rRNA    111                             5S ribosomal RNA
AMFJKEBI_00003  rRNA    2878                            23S ribosomal RNA
AMFJKEBI_00004  tRNA    76                              tRNA-Ala(tgc)
AMFJKEBI_00005  tRNA    77                              tRNA-Ile(gat)
AMFJKEBI_00006  rRNA    1549                            16S ribosomal RNA

## Genomic arrangement of repeats
### Run the alignment
```bash
ln -s ../quast/vibrio/vibrio.fna .
```
Run minimap2
```
minimap2 -x map-ont vibrio.fna repeat.fasta > repeat_vs_genome.paf
```

### Examine the alignment
```bash
head  repeat_vs_genome.paf
```
Extract columns specifying the start and end point on the target
```bash
cat repeat_vs_genome.paf | grep '^repe' | awk -F '\t' '{print $6,$8,$9}' > repeat_locations.bed
```








